---
- hosts: all
  # become: true
  # become_user: root
  gather_facts: false
  tasks:

  - name: install packeges
    community.general.apk:
      name: git, nano
      update_cache: yes
      state: present

