---
- hosts: web
  become: true
  become_user: root
  strategy: free
  vars:
    app_user: "apache"
    http_host: "test"
    http_port: "80"
  tasks:
    - name: httpd installed
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: document root exist
      ansible.builtin.file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'
        setype: "httpd_sys_content_t"

    - name: custom index.html
      ansible.builtin.copy:
        dest: "/var/www/{{ http_host }}/index.html"
        content: |
                    Custom Web Page
                    
    - name: httpd service enabled
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: restarted

    - name: open firewall
      ansible.posix.firewalld:
        service: http
        state: enabled
        immediate: true
        permanent: true